[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"
authors = ["dotanuki.labs@gmail.com"]
description = "Evaluate provenance and reproducibility of your Rust supply chain"
repository = "https://github.com/dotanuki-labs/pollux"
homepage = "https://github.com/dotanuki-labs/pollux"
documentation = "https://github.com/dotanuki-labs/pollux"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "security"]

[workspace.dependencies]
pollux = { path = "crates/pollux" }
xtasks = { path = "crates/xtasks" }

anyhow = "=1.0.100"
assertor = "=0.0.4"
assert_cmd = "=2.0.17"
better-panic = "=0.3.0"
cargo-lock = "=10.1.0"
clap = "=4.5.48"
console = "=0.16.1"
env_logger = "=0.11.8"
futures = "=0.3.31"
hex = "=0.4.3"
httpmock = "=0.7.0"
human-panic = "=2.0.3"
log = "0.4.28"
serde = { version = "=1.0.225", features = ["derive"] }
serde_json = "=1.0.145"
reqwest = { version = "=0.12.23", default-features = false, features = ["json", "rustls-tls", "charset", "system-proxy", "http2"] }
predicates = "=3.1.3"
sha2 = "=0.10.9"
temp-dir = "=0.1.16"
tikv-jemallocator = "0.6.0"
tokio = { version = "=1.47.1", features = ["full"] }
xshell = "=0.2.7"
walkdir = "=2.5.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
