# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd-docs

on:
  workflow_call:

jobs:
  deploy-pages:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Configure Github Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Generate pollux report
        run: |
          RUST_LOG=info cargo run --bin pollux -- inquire --output html --coverage large
          mkdir -p report && mv pollux-report.html report/index.html

      - name: Upload assets Github Pages assets
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: report

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
