# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-compliance

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 20
          persist-credentials: false

      - name: Check typos on source files
        uses: crate-ci/typos@1a319b54cc9e3b333fed6a5c88ba1a90324da514 # v1.40.1

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@9865da4f86a4523e4a80597d7760763d86adafd8 # v1.1.9

      - name: Check MIT license on source files
        uses: korandoru/hawkeye@2f80559b06187bcd1aa7bca5138fe5e5c53e275f # v6.3.0

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          advanced-security: false

