# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-compliance

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 20
          persist-credentials: false

      - name: Check typos on source files
        uses: crate-ci/typos@3a4d65230db538caabac6e156599c8ba8380ff07 # v1.43.1

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@dc6f20ddd899fe6d6f0402807884c0a4b3176b53 # v1.1.10

      - name: Check MIT license on source files
        uses: korandoru/hawkeye@9f58c8ed5347f5dbe58a4a393aaea2be293d6bda # v6.4.1

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          advanced-security: false

