# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

jobs:
  lint-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Restore pollux cache
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ runner.os }}-pollux-cache
          path: /home/runner/.pollux

      - name: Lint Markdown files
        uses: rvben/rumdl@64b8445eb08cbbab1f8525dc2847cfcbbd42e233 # v0.1.7

      - name: Configure Github Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.1

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Generate pollux report (small)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          RUST_LOG=info cargo run --bin pollux -- inquire --output html --coverage small
          mkdir -p report && mv pollux-report.html report/index.html

      - name: Generate pollux report (large)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          RUST_LOG=info cargo run --bin pollux -- inquire --output html --coverage large
          mkdir -p report && mv pollux-report.html report/index.html

      - name: Upload assets Github Pages assets
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: report

      - name: Deploy assets to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

      - name: Save pollux cache
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ runner.os }}-pollux-cache
          path: /home/runner/.pollux
