# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

jobs:
  lint-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Restore pollux cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ runner.os }}-pollux-cache
          path: /home/runner/.pollux

      - name: Lint Markdown files
        uses: dotanuki-labs/github-actions/quality/markdown@771d6c7a54dca1c45d374cade8f9f5ff13f82782

      - name: Configure Github Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Generate pollux report (small)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          RUST_LOG=info cargo run --bin pollux -- inquire --output html --coverage small
          mkdir -p report && mv pollux-report.html report/index.html

      - name: Generate pollux report (large)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          RUST_LOG=info cargo run --bin pollux -- inquire --output html --coverage large
          mkdir -p report && mv pollux-report.html report/index.html

      - name: Upload assets Github Pages assets
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: report

      - name: Deploy assets to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

      - name: Save pollux cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ runner.os }}-pollux-cache
          path: /home/runner/.pollux
